from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views


def protegida(view):
    return login_required(view)

urlpatterns = [
    path('login/audio-aviso-pago/', views.login_aviso_pago_audio, name='login_aviso_pago_audio'),
    path('login/', views.login_usuario, name='login'),
    path('logout/', views.logout_usuario, name='logout'),
    path('', protegida(views.dashboard), name='dashboard'),
    path('chat/', protegida(views.chat_page), name='chat_page'),
    path('tareas/', protegida(views.tareas_page), name='tareas_page'),
    path('whatsapp/', protegida(views.whatsapp_page), name='whatsapp_page'),
    path('facebook/', protegida(views.facebook_page), name='facebook_page'),
    path('voz/', protegida(views.voz_page), name='voz_page'),
    path('configurar/', protegida(views.configurar_perfil), name='configurar_perfil'),
    path('usuarios/', protegida(views.usuarios_page), name='usuarios_page'),
    path('webhook/whatsapp/', views.webhook_whatsapp, name='webhook_whatsapp'),
    path('webhook/facebook/', views.webhook_facebook, name='webhook_facebook'),
    path('api/facebook/config/', protegida(views.facebook_config), name='facebook_config'),
    path('api/facebook/configuracion/', protegida(views.facebook_configuracion), name='facebook_configuracion'),
    path('api/facebook/mensajes/', protegida(views.facebook_mensajes), name='facebook_mensajes'),
    path('api/facebook/conversacion/<int:conversacion_id>/', protegida(views.facebook_conversacion_detalle), name='facebook_conversacion_detalle'),
    path('api/facebook/conversacion/<int:conversacion_id>/enviar/', protegida(views.facebook_conversacion_enviar), name='facebook_conversacion_enviar'),
    path('api/facebook/mensaje/<int:mensaje_id>/', protegida(views.whatsapp_mensaje_detalle), name='facebook_mensaje_detalle'),
    path('api/facebook/borrar-memoria/', protegida(views.facebook_borrar_memoria), name='facebook_borrar_memoria'),
    path('api/whatsapp/conectar-linea/', protegida(views.whatsapp_conectar_linea), name='whatsapp_conectar_linea'),
    path('api/whatsapp/sesiones/', protegida(views.whatsapp_sesiones), name='whatsapp_sesiones'),
    path('api/whatsapp/iniciar-todo/', protegida(views.whatsapp_iniciar_todo), name='whatsapp_iniciar_todo'),
    path('api/whatsapp/estado-linea/<str:linea>/', protegida(views.whatsapp_estado_linea), name='whatsapp_estado_linea'),
    path('api/whatsapp/qr-linea/<str:linea>/', protegida(views.whatsapp_qr_linea), name='whatsapp_qr_linea'),
    path('api/whatsapp/desconectar-linea/<str:linea>/', protegida(views.whatsapp_desconectar_linea), name='whatsapp_desconectar_linea'),
    path('api/whatsapp/borrar-memoria/', protegida(views.whatsapp_borrar_memoria), name='whatsapp_borrar_memoria'),
    path('api/whatsapp/config-lineas/', protegida(views.whatsapp_config_lineas), name='whatsapp_config_lineas'),
    path('api/whatsapp/borrar-sesion/', protegida(views.whatsapp_borrar_sesion), name='whatsapp_borrar_sesion'),
    path('api/whatsapp/eliminar-linea/', protegida(views.whatsapp_eliminar_linea), name='whatsapp_eliminar_linea'),
    path('api/whatsapp/programar-masivo/', protegida(views.whatsapp_programar_masivo), name='whatsapp_programar_masivo'),
    path('api/chat/', protegida(views.chat_directo), name='chat_directo'),
    path('api/chat/historial/', protegida(views.chat_historial), name='chat_historial'),
    path('api/mensajes/', protegida(views.mensajes_recientes), name='mensajes_recientes'),
    path('api/whatsapp/conversacion/<int:conversacion_id>/', protegida(views.whatsapp_conversacion_detalle), name='whatsapp_conversacion_detalle'),
    path('api/whatsapp/conversacion/<int:conversacion_id>/enviar/', protegida(views.whatsapp_conversacion_enviar), name='whatsapp_conversacion_enviar'),
    path('api/whatsapp/mensaje/<int:mensaje_id>/', protegida(views.whatsapp_mensaje_detalle), name='whatsapp_mensaje_detalle'),
    path('api/whatsapp/estadisticas/', protegida(views.whatsapp_estadisticas), name='whatsapp_estadisticas'),
    path('api/voces/', protegida(views.voces_disponibles), name='voces_disponibles'),
    path('api/voz/actualizar/', protegida(views.actualizar_voz), name='actualizar_voz'),
    path('api/voz/actual/', protegida(views.obtener_voz_actual), name='obtener_voz_actual'),
    path('api/tareas/', protegida(views.tareas_listar), name='tareas_listar'),
    path('api/tareas/<str:tarea_id>/', protegida(views.tarea_detalle), name='tarea_detalle'),
    path('api/tareas/<str:tarea_id>/resumen-voz/', protegida(views.tarea_resumen_voz), name='tarea_resumen_voz'),
    path('api/acciones/ejecutar/', protegida(views.ejecutar_accion_pendiente), name='ejecutar_accion_pendiente'),
    path('api/terminal/ejecutar/', protegida(views.terminal_ejecutar), name='terminal_ejecutar'),
    path('api/terminal/permisos/', protegida(views.gestion_permisos), name='gestion_permisos'),
    path('api/devtools/', protegida(views.devtools_accion), name='devtools_accion'),

    # Alarmas y Tareas Programadas
    path('api/alarmas/crear/', protegida(views.crear_alarma), name='crear_alarma'),
    path('api/alarmas/', protegida(views.listar_alarmas), name='listar_alarmas'),
    path('api/alarmas/todas/', protegida(views.listar_todas_tareas), name='listar_todas_tareas'),
    path('api/alarmas/resumen/', protegida(views.alarmas_resumen), name='alarmas_resumen'),
    path('api/alarmas/<int:tarea_id>/cancelar/', protegida(views.cancelar_alarma), name='cancelar_alarma'),
    path('api/scheduler/iniciar/', protegida(views.scheduler_iniciar), name='scheduler_iniciar'),
]
