from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('chat/', views.chat_page, name='chat_page'),
    path('tareas/', views.tareas_page, name='tareas_page'),
    path('whatsapp/', views.whatsapp_page, name='whatsapp_page'),
    path('voz/', views.voz_page, name='voz_page'),
    path('configurar/', views.configurar_perfil, name='configurar_perfil'),
    path('webhook/whatsapp/', views.webhook_whatsapp, name='webhook_whatsapp'),
    path('api/whatsapp/conectar-linea/', views.whatsapp_conectar_linea, name='whatsapp_conectar_linea'),
    path('api/whatsapp/sesiones/', views.whatsapp_sesiones, name='whatsapp_sesiones'),
    path('api/whatsapp/iniciar-todo/', views.whatsapp_iniciar_todo, name='whatsapp_iniciar_todo'),
    path('api/whatsapp/estado-linea/<str:linea>/', views.whatsapp_estado_linea, name='whatsapp_estado_linea'),
    path('api/whatsapp/qr-linea/<str:linea>/', views.whatsapp_qr_linea, name='whatsapp_qr_linea'),
    path('api/whatsapp/desconectar-linea/<str:linea>/', views.whatsapp_desconectar_linea, name='whatsapp_desconectar_linea'),
    path('api/whatsapp/borrar-memoria/', views.whatsapp_borrar_memoria, name='whatsapp_borrar_memoria'),
    path('api/whatsapp/config-lineas/', views.whatsapp_config_lineas, name='whatsapp_config_lineas'),
    path('api/whatsapp/borrar-sesion/', views.whatsapp_borrar_sesion, name='whatsapp_borrar_sesion'),
    path('api/whatsapp/eliminar-linea/', views.whatsapp_eliminar_linea, name='whatsapp_eliminar_linea'),
    path('api/chat/', views.chat_directo, name='chat_directo'),
    path('api/chat/historial/', views.chat_historial, name='chat_historial'),
    path('api/mensajes/', views.mensajes_recientes, name='mensajes_recientes'),
    path('api/whatsapp/estadisticas/', views.whatsapp_estadisticas, name='whatsapp_estadisticas'),
    path('api/voces/', views.voces_disponibles, name='voces_disponibles'),
    path('api/voz/actualizar/', views.actualizar_voz, name='actualizar_voz'),
    path('api/voz/actual/', views.obtener_voz_actual, name='obtener_voz_actual'),
    path('api/tareas/', views.tareas_listar, name='tareas_listar'),
    path('api/tareas/<str:tarea_id>/', views.tarea_detalle, name='tarea_detalle'),
    path('api/tareas/<str:tarea_id>/resumen-voz/', views.tarea_resumen_voz, name='tarea_resumen_voz'),
    path('api/acciones/ejecutar/', views.ejecutar_accion_pendiente, name='ejecutar_accion_pendiente'),
    path('api/terminal/ejecutar/', views.terminal_ejecutar, name='terminal_ejecutar'),
    path('api/terminal/permisos/', views.gestion_permisos, name='gestion_permisos'),
    path('api/devtools/', views.devtools_accion, name='devtools_accion'),

    # Alarmas y Tareas Programadas
    path('api/alarmas/crear/', views.crear_alarma, name='crear_alarma'),
    path('api/alarmas/', views.listar_alarmas, name='listar_alarmas'),
    path('api/alarmas/todas/', views.listar_todas_tareas, name='listar_todas_tareas'),
    path('api/alarmas/resumen/', views.alarmas_resumen, name='alarmas_resumen'),
    path('api/alarmas/<int:tarea_id>/cancelar/', views.cancelar_alarma, name='cancelar_alarma'),
    path('api/scheduler/iniciar/', views.scheduler_iniciar, name='scheduler_iniciar'),
]
