# Generated by Django 6.0.5 on 2026-05-11 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_whatsapp', models.CharField(max_length=30)),
                ('nombre_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asistente', models.CharField(default='Asistente', max_length=100)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('cv_archivo', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('cv_texto', models.TextField(blank=True, null=True)),
                ('prompt_sistema', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil del Asistente',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('voz', 'Voz'), ('imagen', 'Imagen')], default='texto', max_length=10)),
                ('origen', models.CharField(choices=[('entrante', 'Entrante'), ('saliente', 'Saliente')], max_length=10)),
                ('contenido', models.TextField()),
                ('audio_url', models.CharField(blank=True, max_length=500, null=True)),
                ('leido', models.BooleanField(default=False)),
                ('respondido', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='asistente.conversacion')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ComandoEjecutado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando', models.TextField()),
                ('resultado', models.TextField(blank=True, null=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('ejecutado_en', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='asistente.mensaje')),
            ],
        ),
        migrations.AddField(
            model_name='conversacion',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='asistente.perfilasistente'),
        ),
    ]
