# Generated by Django 6.0.5 on 2026-05-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilasistente',
            name='voz_preferida',
            field=models.CharField(default='es-CO-SalomeNeural', help_text='Código de voz TTS', max_length=100),
        ),
        migrations.AddField(
            model_name='perfilasistente',
            name='voz_velocidad',
            field=models.FloatField(default=1.0, help_text='Velocidad de reproducción (0.5 - 2.0)'),
        ),
    ]
