# Generated by Django 6.0.5 on 2026-05-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0002_perfilasistente_voz_preferida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilasistente',
            name='voz_preferida',
            field=models.CharField(default='piper:carlos', help_text='Código de voz TTS', max_length=100),
        ),
    ]
