# Generated by Django 6.0.5 on 2026-05-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0003_auto_20260511_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilasistente',
            name='voz_preferida',
            field=models.CharField(default='parler:bill', help_text='Código de voz TTS', max_length=100),
        ),
    ]
