# Generated by Django 6.0.5 on 2026-05-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0004_alter_perfilasistente_voz_preferida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilasistente',
            name='voz_preferida',
            field=models.CharField(default='es-CO-GonzaloNeural', help_text='Código de voz TTS', max_length=100),
        ),
    ]
