# Generated by Django 6.0.5 on 2026-05-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0010_alter_perfilasistente_voz_preferida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilasistente',
            name='voz_preferida',
            field=models.CharField(default='aura-javier-es', help_text='Código de voz TTS (Deepgram Aura, Edge-TTS, o Offline)', max_length=100),
        ),
    ]
