# Generated by Django 6.0.5 on 2026-05-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0015_alter_perfilasistente_voz_preferida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilasistente',
            name='voz_preferida',
            field=models.CharField(default='piper:es_ES-mls_10246-low', help_text='Código de voz TTS (Piper gratis, Deepgram Aura, Edge-TTS, u Offline)', max_length=100),
        ),
    ]
