# Generated by Django 6.0.5 on 2026-05-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0017_alter_perfilasistente_voz_preferida'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilasistente',
            name='comandos_personalizados',
            field=models.TextField(blank=True, help_text='JSON con comandos adicionales permitidos', null=True),
        ),
    ]
