# Generated by Django 6.0.5 on 2026-05-13 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0018_perfilasistente_comandos_personalizados'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_accion', models.CharField(choices=[('recordatorio', 'Recordatorio simple'), ('whatsapp', 'Enviar mensaje WhatsApp'), ('comando_pc', 'Ejecutar comando PC'), ('url', 'Abrir URL'), ('sistema', 'Acción de sistema (bloquear, suspender, etc.)')], max_length=20)),
                ('parametros', models.JSONField(default=dict)),
                ('programado_para', models.DateTimeField(db_index=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutando', 'Ejecutando'), ('completada', 'Completada'), ('fallida', 'Fallida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ejecutado_en', models.DateTimeField(blank=True, null=True)),
                ('repetir', models.CharField(blank=True, help_text='Patrón de repetición: "diario", "semanal", "mensual", o expresión cron', max_length=20, null=True)),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_programadas', to='asistente.perfilasistente')),
            ],
            options={
                'verbose_name': 'Tarea Programada',
                'verbose_name_plural': 'Tareas Programadas',
                'ordering': ['programado_para'],
                'indexes': [models.Index(fields=['estado', 'programado_para'], name='asistente_t_estado_c5920d_idx')],
            },
        ),
    ]
