# Generated by Django 6.0.5 on 2026-05-19 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0020_alter_conversacion_numero_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilasistente',
            options={'verbose_name': 'Perfil del Asistente', 'verbose_name_plural': 'Perfiles del Asistente'},
        ),
        migrations.AddField(
            model_name='perfilasistente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_asistente', to=settings.AUTH_USER_MODEL),
        ),
    ]
