# Generated by Django 6.0.5 on 2026-05-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0021_alter_perfilasistente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilasistente',
            name='meta_app_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='perfilasistente',
            name='meta_graph_api_version',
            field=models.CharField(blank=True, default='v25.0', max_length=20),
        ),
        migrations.AddField(
            model_name='perfilasistente',
            name='meta_page_access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='perfilasistente',
            name='meta_page_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='perfilasistente',
            name='meta_verify_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='perfilasistente',
            name='meta_webhook_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
