# Generated by Django 6.0.5 on 2026-05-22 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0022_perfilasistente_meta_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(db_index=True)),
                ('duracion_minutos', models.PositiveIntegerField(default=60, help_text='Duración en minutos')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_ubicacion', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('telefonica', 'Telefónica')], default='presencial', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('recordatorio_minutos_antes', models.PositiveIntegerField(default=5)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('conversacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='asistente.conversacion')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='asistente.perfilasistente')),
                ('tarea_recordatorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_asociada', to='asistente.tareaprogramada')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_hora'],
                'indexes': [models.Index(fields=['estado', 'fecha_hora'], name='asistente_c_estado_d8e2d0_idx')],
            },
        ),
    ]
